(define (problem multitasking43)
	(:domain multitaskingeasy)
	(:objects
		Dish0 Dish1 Dish2  - dish
		Ingredient0 Ingredient1 Ingredient2 Ingredient3 Ingredient4 Ingredient5 Ingredient6 Ingredient7 Ingredient8  - ingredient
		Room0 Room1 Room2 Room3  - room
		CookingTool0  - cookingtool
		CleaningTool0 CleaningTool1  - cleaningtool
		GardeningTool0  - gardeningtool
		Plant0 Plant1 Plant2  - plant
)
	(:init
		(ingr1 Ingredient2 Dish0)
		(ingr2 Ingredient1 Dish0)
		(ingr3 Ingredient0 Dish0)
		(needed CookingTool0 Dish0)
		(ingr1 Ingredient5 Dish1)
		(ingr2 Ingredient4 Dish1)
		(ingr3 Ingredient3 Dish1)
		(needed CookingTool0 Dish1)
		(ingr1 Ingredient8 Dish2)
		(ingr2 Ingredient7 Dish2)
		(ingr3 Ingredient6 Dish2)
		(needed CookingTool0 Dish2)
		(at Ingredient0 Room2)
		(at Ingredient1 Room1)
		(at Ingredient2 Room2)
		(at Ingredient3 Room3)
		(at Ingredient4 Room3)
		(at Ingredient5 Room0)
		(at Ingredient6 Room2)
		(at Ingredient7 Room2)
		(at Ingredient8 Room0)
		(connected Room0 Room3)
		(connected Room1 Room0)
		(connected Room2 Room1)
		(connected Room3 Room2)
		(position Room3)
		(at CookingTool0 Room0)
		(at CleaningTool0 Room2)
		(at CleaningTool1 Room1)
		(at GardeningTool0 Room3)
		(at Plant0 Room2)
		(at Plant1 Room1)
		(at Plant2 Room3)
	)
	(:goal (and
		(clean Room1)
		(clean Room2)
		(clean Room0)
		(clean Room3)
		(gardened Plant2)
		(gardened Plant0)
		(gardened Plant1)
	))
)