(define (problem depotprob32606) (:domain depot)
(:objects
	depot0 depot1 depot2 depot3 depot4 depot5 - Depot
	distributor0 distributor1 distributor2 distributor3 distributor4 distributor5 - Distributor
	truck0 truck1 truck2 truck3 truck4 - Truck
	pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 pallet6 pallet7 pallet8 pallet9 pallet10 pallet11 - Pallet
	crate0 crate1 crate2 crate3 crate4 crate5 - Crate
	hoist0 hoist1 hoist2 hoist3 hoist4 hoist5 hoist6 hoist7 hoist8 hoist9 hoist10 hoist11 - Hoist
	dummy_depot0 dummy_depot1 dummy_depot2 dummy_depot3 - Depot
	dummy_distributor0 dummy_distributor1 dummy_distributor2 dummy_distributor3 dummy_distributor4 dummy_distributor5 dummy_distributor6 dummy_distributor7 dummy_distributor8 - Distributor
	dummy_trucks0 dummy_trucks1 dummy_trucks2 dummy_trucks3 dummy_trucks4 dummy_trucks5 dummy_trucks6 - Truck
	dummy_pallet0 dummy_pallet1 dummy_pallet2 dummy_pallet3 dummy_pallet4 dummy_pallet5 dummy_pallet6 dummy_pallet7 dummy_pallet8 dummy_pallet9 dummy_pallet10 dummy_pallet11 dummy_pallet12 dummy_pallet13 dummy_pallet14 - Pallet
	dummy_crate0 dummy_crate1 dummy_crate2 dummy_crate3 dummy_crate4 dummy_crate5 dummy_crate6 dummy_crate7 dummy_crate8 dummy_crate9 dummy_crate10 dummy_crate11 dummy_crate12 dummy_crate13 dummy_crate14 dummy_crate15 dummy_crate16 dummy_crate17 dummy_crate18 dummy_crate19 dummy_crate20 dummy_crate21 dummy_crate22 dummy_crate23 - Crate
	dummy_hoist0 dummy_hoist1 dummy_hoist2 dummy_hoist3 dummy_hoist4 dummy_hoist5 dummy_hoist6 dummy_hoist7 dummy_hoist8 dummy_hoist9 - Hoist
	)
(:init
	(at pallet0 depot0)
	(clear pallet0)
	(at pallet1 depot1)
	(clear pallet1)
	(at pallet2 depot2)
	(clear crate5)
	(at pallet3 depot3)
	(clear pallet3)
	(at pallet4 depot4)
	(clear crate2)
	(at pallet5 depot5)
	(clear pallet5)
	(at pallet6 distributor0)
	(clear pallet6)
	(at pallet7 distributor1)
	(clear crate3)
	(at pallet8 distributor2)
	(clear pallet8)
	(at pallet9 distributor3)
	(clear pallet9)
	(at pallet10 distributor4)
	(clear crate4)
	(at pallet11 distributor5)
	(clear crate1)
	(at truck0 distributor2)
	(at truck1 depot0)
	(at truck2 depot3)
	(at truck3 distributor3)
	(at truck4 depot5)
	(at hoist0 depot0)
	(available hoist0)
	(at hoist1 depot1)
	(available hoist1)
	(at hoist2 depot2)
	(available hoist2)
	(at hoist3 depot3)
	(available hoist3)
	(at hoist4 depot4)
	(available hoist4)
	(at hoist5 depot5)
	(available hoist5)
	(at hoist6 distributor0)
	(available hoist6)
	(at hoist7 distributor1)
	(available hoist7)
	(at hoist8 distributor2)
	(available hoist8)
	(at hoist9 distributor3)
	(available hoist9)
	(at hoist10 distributor4)
	(available hoist10)
	(at hoist11 distributor5)
	(available hoist11)
	(at crate0 distributor5)
	(on crate0 pallet11)
	(at crate1 distributor5)
	(on crate1 crate0)
	(at crate2 depot4)
	(on crate2 pallet4)
	(at crate3 distributor1)
	(on crate3 pallet7)
	(at crate4 distributor4)
	(on crate4 pallet10)
	(at crate5 depot2)
	(on crate5 pallet2)
	(at dummy_trucks0 dummy_depot0)
	(at dummy_trucks1 dummy_depot1)
	(at dummy_trucks2 dummy_depot0)
	(at dummy_trucks3 dummy_distributor0)
	(at dummy_trucks4 dummy_distributor0)
	(at dummy_trucks5 dummy_depot0)
	(at dummy_trucks6 dummy_distributor1)
	(at dummy_hoist0 dummy_distributor5)
	(at dummy_hoist1 dummy_distributor2)
	(at dummy_hoist2 dummy_depot2)
	(at dummy_hoist3 dummy_distributor2)
	(at dummy_hoist4 dummy_distributor6)
	(at dummy_hoist5 dummy_depot2)
	(at dummy_hoist6 dummy_distributor6)
	(at dummy_hoist7 dummy_depot2)
	(at dummy_hoist8 dummy_depot0)
	(at dummy_hoist9 dummy_depot3)
	(at dummy_pallet0 dummy_distributor0)
	(at dummy_pallet1 dummy_depot2)
	(at dummy_pallet2 dummy_distributor0)
	(at dummy_pallet3 dummy_distributor8)
	(at dummy_pallet4 dummy_depot3)
	(at dummy_pallet5 dummy_depot1)
	(at dummy_pallet6 dummy_distributor2)
	(at dummy_pallet7 dummy_distributor4)
	(at dummy_pallet8 dummy_distributor5)
	(at dummy_pallet9 dummy_depot2)
	(at dummy_pallet10 dummy_distributor0)
	(at dummy_pallet11 dummy_depot1)
	(at dummy_pallet12 dummy_depot2)
	(at dummy_pallet13 dummy_distributor0)
	(at dummy_pallet14 dummy_distributor1)
	(at dummy_crate0 dummy_depot0)
	(at dummy_crate1 dummy_distributor3)
	(at dummy_crate2 dummy_depot2)
	(at dummy_crate3 dummy_depot3)
	(at dummy_crate4 dummy_distributor3)
	(at dummy_crate5 dummy_depot0)
	(at dummy_crate6 dummy_depot1)
	(at dummy_crate7 dummy_distributor8)
	(at dummy_crate8 dummy_depot1)
	(at dummy_crate9 dummy_depot0)
	(at dummy_crate10 dummy_depot1)
	(at dummy_crate11 dummy_distributor4)
	(at dummy_crate12 dummy_distributor5)
	(at dummy_crate13 dummy_depot2)
	(at dummy_crate14 dummy_distributor0)
	(at dummy_crate15 dummy_depot0)
	(at dummy_crate16 dummy_distributor6)
	(at dummy_crate17 dummy_depot1)
	(at dummy_crate18 dummy_distributor7)
	(at dummy_crate19 dummy_depot1)
	(at dummy_crate20 dummy_distributor5)
	(at dummy_crate21 dummy_distributor0)
	(at dummy_crate22 dummy_distributor0)
	(at dummy_crate23 dummy_depot1)
	(on dummy_crate0 dummy_crate15)
	(on dummy_crate1 dummy_crate4)
	(on dummy_crate2 dummy_crate13)
	(on dummy_crate3 dummy_pallet4)
	(on dummy_crate6 dummy_pallet11)
	(on dummy_crate7 dummy_pallet3)
	(on dummy_crate8 dummy_pallet5)
	(on dummy_crate11 dummy_pallet7)
	(on dummy_crate12 dummy_pallet8)
	(on dummy_crate13 dummy_crate2)
	(on dummy_crate14 dummy_crate21)
	(on dummy_crate15 dummy_crate9)
	(on dummy_crate21 dummy_pallet13)
	(on dummy_crate22 dummy_crate14)
	(on dummy_crate23 dummy_crate8)
	(available dummy_hoist0)
	(available dummy_hoist1)
	(available dummy_hoist2)
	(available dummy_hoist3)
	(available dummy_hoist4)
	(available dummy_hoist5)
	(available dummy_hoist6)
	(available dummy_hoist7)
	(available dummy_hoist8)
	(available dummy_hoist9)
	(clear dummy_crate0)
	(clear dummy_crate1)
	(clear dummy_crate3)
	(clear dummy_crate5)
	(clear dummy_crate6)
	(clear dummy_crate7)
	(clear dummy_crate10)
	(clear dummy_crate11)
	(clear dummy_crate12)
	(clear dummy_crate16)
	(clear dummy_crate17)
	(clear dummy_crate18)
	(clear dummy_crate19)
	(clear dummy_crate20)
	(clear dummy_crate22)
	(clear dummy_crate23)
	(clear dummy_pallet0)
	(clear dummy_pallet1)
	(clear dummy_pallet2)
	(clear dummy_pallet6)
	(clear dummy_pallet9)
	(clear dummy_pallet10)
	(clear dummy_pallet12)
	(clear dummy_pallet14)
)

(:goal (and
		(on crate0 pallet5)
		(on crate1 crate2)
		(on crate2 pallet8)
		(on crate3 pallet9)
		(on crate4 pallet2)
	)
))
