(define (problem multitasking23)
	(:domain multitasking)
	(:objects
		Dish0 Dish1  - dish
		Ingredient0 Ingredient1 Ingredient2 Ingredient3 Ingredient4 Ingredient5 Ingredient6 Ingredient7  - ingredient
		Room0 Room1 Room2 Room3  - room
		CookingTool0 CookingTool1 CookingTool2 CookingTool3  - cookingtool
		CleaningTool0 CleaningTool1  - cleaningtool
		GardeningTool0  - gardeningtool
		Plant0 Plant1 Plant2  - plant
)
	(:init
		(ingr1 Ingredient2 Dish0)
		(ingr2 Ingredient1 Dish0)
		(ingr3 Ingredient0 Dish0)
		(needed CookingTool1 Dish0)
		(ingr1 Ingredient5 Dish1)
		(ingr2 Ingredient4 Dish1)
		(ingr3 Ingredient3 Dish1)
		(needed CookingTool2 Dish1)
		(at Ingredient0 Room3)
		(at Ingredient1 Room3)
		(at Ingredient2 Room3)
		(at Ingredient3 Room1)
		(at Ingredient4 Room3)
		(at Ingredient5 Room1)
		(at Ingredient6 Room3)
		(at Ingredient7 Room1)
		(connected Room0 Room3)
		(position Room0)
		(connected Room1 Room0)
		(connected Room2 Room1)
		(connected Room3 Room2)
		(at CookingTool0 Room2)
		(at CookingTool1 Room0)
		(at CookingTool2 Room0)
		(at CookingTool3 Room3)
		(at CleaningTool0 Room1)
		(at CleaningTool1 Room3)
		(at GardeningTool0 Room1)
		(at Plant0 Room0)
		(at Plant1 Room1)
		(at Plant2 Room2)
		(handfree)
	)
	(:goal (and
		(cooked Dish0)
		(cooked Dish1)
		(washed CookingTool0)
		(washed CookingTool1)
		(washed CookingTool2)
		(washed CookingTool3)
		(clean Room2)
		(clean Room1)
		(clean Room0)
		(clean Room3)
	))
)