(define (problem multitasking7)
	(:domain multitasking)
	(:objects
		Dish0 Dish1 Dish2 Dish3  - dish
		Ingredient0 Ingredient1 Ingredient2 Ingredient3 Ingredient4 Ingredient5 Ingredient6 Ingredient7 Ingredient8 Ingredient9 Ingredient10 Ingredient11  - ingredient
		Room0 Room1 Room2 Room3 Room4  - room
		CookingTool0 CookingTool1  - cookingtool
		CleaningTool0 CleaningTool1 CleaningTool2  - cleaningtool
		GardeningTool0 GardeningTool1  - gardeningtool
		Plant0 Plant1 Plant2 Plant3  - plant
)
	(:init
		(ingr1 Ingredient2 Dish0)
		(ingr2 Ingredient1 Dish0)
		(ingr3 Ingredient0 Dish0)
		(needed CookingTool1 Dish0)
		(ingr1 Ingredient5 Dish1)
		(ingr2 Ingredient4 Dish1)
		(ingr3 Ingredient3 Dish1)
		(needed CookingTool0 Dish1)
		(ingr1 Ingredient8 Dish2)
		(ingr2 Ingredient7 Dish2)
		(ingr3 Ingredient6 Dish2)
		(needed CookingTool0 Dish2)
		(ingr1 Ingredient11 Dish3)
		(ingr2 Ingredient10 Dish3)
		(ingr3 Ingredient9 Dish3)
		(needed CookingTool1 Dish3)
		(at Ingredient0 Room3)
		(at Ingredient1 Room0)
		(at Ingredient2 Room1)
		(at Ingredient3 Room0)
		(at Ingredient4 Room2)
		(at Ingredient5 Room4)
		(at Ingredient6 Room2)
		(at Ingredient7 Room4)
		(at Ingredient8 Room3)
		(at Ingredient9 Room0)
		(at Ingredient10 Room4)
		(at Ingredient11 Room4)
		(connected Room0 Room4)
		(connected Room1 Room0)
		(position Room1)
		(connected Room2 Room1)
		(connected Room3 Room2)
		(connected Room4 Room3)
		(at CookingTool0 Room1)
		(at CookingTool1 Room1)
		(at CleaningTool0 Room0)
		(at CleaningTool1 Room0)
		(at CleaningTool2 Room2)
		(at GardeningTool0 Room0)
		(at GardeningTool1 Room1)
		(at Plant0 Room1)
		(at Plant1 Room3)
		(at Plant2 Room0)
		(at Plant3 Room3)
		(handfree)
	)
	(:goal (and
		(cooked Dish0)
		(cooked Dish3)
		(cooked Dish2)
		(washed CookingTool0)
		(washed CookingTool1)
		(clean Room2)
		(clean Room0)
		(clean Room3)
		(clean Room1)
		(clean Room4)
	))
)