(define   (problem parking)  (:domain manyparking)
  (:objects
     car_0  car_1  car_2  car_3  car_4  car_5  car_6  car_7  car_8 - car
     curb_0 curb_1 curb_2 curb_3 curb_4 curb_5 curb_6 curb_7 - curb
	)  (:init
    (at-curb car_2)
    (at-curb-num car_2 curb_0)
    (behind-car car_0 car_2)
    (car-clear car_0)
    (at-curb car_6)
    (at-curb-num car_6 curb_1)
    (behind-car car_3 car_6)
    (car-clear car_3)
    (at-curb car_5)
    (at-curb-num car_5 curb_2)
    (behind-car car_8 car_5)
    (car-clear car_8)
    (at-curb car_7)
    (at-curb-num car_7 curb_3)
    (car-clear car_7)
    (at-curb car_1)
    (at-curb-num car_1 curb_4)
    (car-clear car_1)
    (at-curb car_4)
    (at-curb-num car_4 curb_5)
    (car-clear car_4)
    (curb-clear curb_6)
    (curb-clear curb_7)
  )
  (:goal     (and
      (behind-car car_8 car_0)
)))